# XGBoost

In [1]:
!pip install plotly

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [9]:
dataset = pd.read_csv('class0.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [10]:
y = y.reshape(len(y),1)

In [11]:
for i in range(0,len(X[:,3])):
    X[i,3]=float(X[i,3].split("-")[0])
    X[i,4]=float(X[i,4].split("-")[0])
    X[i,5]=float(X[i,5].split("-")[0])
    X[i,6]=float(X[i,6].split("-")[0])
    X[i,7]=float(X[i,7].split("-")[0])
    X[i,8]=float(X[i,8].split("-")[0])
print(X)

[[1 30.94 20 ... 0.14 0.32 0.27]
 [2 30.94 20 ... 3.98 9.57 5.6]
 [3 31.96 20 ... 4.1 9.69 5.71]
 ...
 [2398 28.82 54 ... 3.93 9.46 3.4]
 [2399 28.82 54 ... 3.94 9.47 3.51]
 [2400 28.82 54 ... 3.99 9.46 3.58]]


## Taking care of Missing Values

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,:])
X[:,:] = imputer.transform(X[:,:])

## Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
xtr=X_train[:,0]
xte=X_test[:,0]
ytr=y_train[:,0]
yte=y_test[:,0]

## Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
print(X_train.shape)

(1600, 9)


## Training the XGBoost model on the Training set

In [15]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

## Predicting the Test set results

In [16]:
y_pred = classifier.predict(X_test)

## Evaluating Results

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   0   0   0   0   0 408]
 [  0   0   0   0   0   0  64]
 [  0   0   0   0   0   0  66]
 [  0   0   0   0   0   0  72]
 [  0   0   0   0   0   0  64]
 [  0   0   0   0   0   0  52]
 [  0   0   0   0   0   0  74]]


0.0925

## Visualising the Training set results

## Visualising the Test set results